### ISSUE TITLE
Why does not yet work?

### ISSUE THREAD

**Issue by danielfttorres** [Gregoor/next.js-relay-example#1]

**Comment by tanekim88** [comment]
It is not working because the developer is underpaid

**Comment by Gregoor** [comment]
@tanekim77 :laughing: I'm good, but thanks.

@danielfeelfine It's not working yet, because I haven't figured out how to make it work. Once I have, I'll update this. Here is an approach, which is apparently working for someone:
https://github.com/zeit/next.js/issues/1757#issuecomment-302443123

btw, sorry for the late response. Just saw this by chance. For some reason I was not getting email notifications

**Comment by steida** [comment]
I think this is the working approach https://github.com/robrichard/relay-query-lookup-renderer

**Comment by tanekim88** [comment]
This is the future of relay modern: 
https://github.com/4Catalyzer/found-relay/tree/master/examples/todomvc-modern-universal

This working example provides relay modern routing with server side rendering.

**Comment by Gregoor** [comment]
Thanks for the links. Have been banging my head against `relay-query-lookup-renderer` for about an hour, but looks like my head is too thick. When I have more time to spare, I'll see if todomvc-modern-universl will help me understand where I go wrong.
